---
# host groups required for kubespray
all:
  children:
    etcd:
      children:
        kube_control_plane:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
        calico_rr:
